#!/bin/bash

######################
GDB_ENABLED=1
GDB=gentest.gdb

TRACE_BEGIN_STRING="SIGSEGV"
TRACE_FILE="crashlog.log"
ERR_FILE="error.log"
SYSLOG="system.log"
SYSERR="error.log"
######################

DATE=$(date)
echo "Starting Gentest ($DATE)"
if [ $GDB_ENABLED -eq 1 ]; then
	./debug core $GDB "$SYSLOG" "$SYSERR" 1
    grep -B 10 -A 1800 "$TRACE_BEGIN_STRING" "$SYSLOG" > "$TRACE_FILE"
fi

if [ $GDB_ENABLED -eq 0 ]; then
	./debug core null null null 0
fi
