#!/bin/bash

######################
GDB="gentest.gdb"

TRACE_BEGIN_STRING="SIGSEGV"
TRACE_FILE="crashlog.log"
SYSLOG="system.log"
SYSERR="error.log"
######################

DATE=$(date)
echo "Starting Gentest ($DATE)"
echo -e "run\nbt\nbt full\ninfo thread\nthread apply all backtrace full" > $GDB

rm $SYSLOG $SYSERR > /dev/null 2>&1
gdb -x $GDB --batch --args ./gentest -p0 >$SYSLOG 2>$SYSERR
grep -B 10 -A 1800 "$TRACE_BEGIN_STRING" "$SYSLOG" > "$TRACE_FILE"

